# Generated by Django 4.1.1 on 2023-05-16 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeapp', '0003_rename_user_userdetails_alter_useractivity_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernutrition',
            name='name',
        ),
        migrations.AlterField(
            model_name='usernutrition',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
