# Generated by Django 4.1.1 on 2023-05-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_usernutrition_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernutrition',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
