# Generated by Django 4.1.1 on 2023-05-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_alter_usernutrition_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernutrition',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
