# Generated by Django 4.1.1 on 2023-05-18 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0013_workout_date_workout_exercises_workout_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='description',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_type',
        ),
    ]
